#include "pm_std.h"
#include "pm_std.h"
#include "mc_std.h"
#include "mc_std.h"
PmSparsityPattern *mc_S33zPe8SknN9LcYhCb5wi0(const PmSparsityPattern *
mc__aqwF2UeMrHkDfRgGhMkr0,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);void
mc_I9gOpdxdkDtFisWaAcueS2(real_T *mc_8VOewhnYPTbEOlk_QYcri_,const
PmSparsityPattern *mc_EosJ0tDP9FinOzz9f3ExR0,const real_T *
mc__lerGssn0Ru_r3kSOzEmI_,const PmSparsityPattern *mc__aqwF2UeMrHkDfRgGhMkr0);
void mc_8PNvEo7OREfPPqdHoj4v91(PmSparsityPattern *mc_zjv8smHIpfaW50M42kA_f0,
PmRealVector *mc_EJqOvdCztL0mVeO_IBz710);PmSparsityPattern *
mc_fs9G14AuSjx6a7_fW1jDc2(const PmSparsityPattern *pm_PJaAk_OAdWPbuizgCm_rK1,
const PmBoolVector *mc_crpmV1NfytxB6epLFDbeY2,const PmBoolVector *
mc_l6yizd46ODo8FXwxtVTrF_,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);
PmSparsityPattern *mc_QrDTyksvE_fzwQPgWfWMo0(const PmSparsityPattern *
pm_PJaAk_OAdWPbuizgCm_rK1,const PmBoolVector *mc_crpmV1NfytxB6epLFDbeY2,const
PmBoolVector *mc_l6yizd46ODo8FXwxtVTrF_,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2
);PmSparsityPattern *mc_lya_e_YIJ3zOEAoJRDe0c1(const PmSparsityPattern *
mc_8ErCt9pDoksttiAw9iBZp_,const PmBoolVector *mc_ID3sxM8zmIB_ZiazgNvWq2,const
PmBoolVector *pm_gq3kPpO4Hdv_0UBmX5sfB1,PmAllocator *mc_J3BYejxvpAX9ghSFCe0tN1
);void mc_UQyLykYxB6RfV3R5UafUE0(const PmRealVector *mc_hZWQ2ZXreN1MIi_7Oc0hF_
,const real_T *mc_He9JzoY7_Zv_2kVxHiuP90,const PmSparsityPattern *
pm_PJaAk_OAdWPbuizgCm_rK1,const PmBoolVector *mc_crpmV1NfytxB6epLFDbeY2,const
PmBoolVector *mc_l6yizd46ODo8FXwxtVTrF_);PmSparsityPattern *
mc_OvyDOAB_3upKwMOnK3EZV1(const PmSparsityPattern *pm_PJaAk_OAdWPbuizgCm_rK1,
size_t mc_N_EjeQp4WJPJRftR0Y3Cd1,size_t mc_iFeOP4BSbdQmZZgCGP03i0,size_t
mc_I98x_QlzPPBua1Isb8hyI0,size_t mc_Q968L5leQKUG_5PDr9DIY2,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);PmSparsityPattern *mc_dCGqQVZgg5nte_jY9_Cd01(const
PmSparsityPattern *pm_PJaAk_OAdWPbuizgCm_rK1,size_t mc_N_EjeQp4WJPJRftR0Y3Cd1,
size_t mc_iFeOP4BSbdQmZZgCGP03i0,size_t mc_I98x_QlzPPBua1Isb8hyI0,size_t
mc_Q968L5leQKUG_5PDr9DIY2,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);void
mc_oA0IbcqlgIdVsQKAmscwa0(const PmRealVector *mc_D8uN6coYCbZ1Qg6YMrSWl_,const
PmRealVector *mc_31d6WAc2j8nDPGeo8k4eo_,const PmSparsityPattern *
pm_PJaAk_OAdWPbuizgCm_rK1,size_t mc_N_EjeQp4WJPJRftR0Y3Cd1,size_t
mc_iFeOP4BSbdQmZZgCGP03i0,size_t mc_I98x_QlzPPBua1Isb8hyI0,size_t
mc_Q968L5leQKUG_5PDr9DIY2);void mc_zxKlKqk_QHLlgCOo_2ImC_(PmSparsityPattern *
mc__aqwF2UeMrHkDfRgGhMkr0,size_t n);void mc_Tdqt4n_f38OzgBkReWoiP1(
PmSparsityPattern *mc__aqwF2UeMrHkDfRgGhMkr0,size_t n);PmSparsityPattern *
mc_4gIlQP6_fYrNISbOZFNkP_(const PmSparsityPattern *pm_Pc8_RQ7nsOlzNUh7aYI680,
size_t n,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);PmSparsityPattern *
mc_83hy7P7oW7aRSDM7TcBsA2(const PmSparsityPattern *pm_Pc8_RQ7nsOlzNUh7aYI680,
size_t n,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);PmSparsityPattern *
mc_PPbEGaGW9CGqvjemmEymj2(const PmSparsityPattern *mc__aqwF2UeMrHkDfRgGhMkr0,
const PmSparsityPattern *mc_VcKY7m0QAr85hALPtvLmC2,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);void mc_SNiMSuxDEldsSjsl5k9Ry1(const PmRealVector *
mc_82a3DKJG1OnqEvQnRrma62,const PmSparsityPattern *mc_d9m7txhohSpkYAQKYp3sR1,
const PmRealVector *mc_frpbnk4Y0M4ZDQTQA_Say1,const PmSparsityPattern *
mc__aqwF2UeMrHkDfRgGhMkr0,const PmRealVector *mc_LvXhgCm6S5lTCS5qnZ0nL0,const
PmSparsityPattern *mc_VcKY7m0QAr85hALPtvLmC2,const PmRealVector *
mc_8oHKE_vHwVdaX05lQda_c1);PmSparsityPattern *mc_pPG5PIgnV_OuwvOl9CVnj_(const
PmSparsityPattern *mc__aqwF2UeMrHkDfRgGhMkr0,const PmSparsityPattern *
mc_VcKY7m0QAr85hALPtvLmC2,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);void
mc_qmyb9URRq9IoJgMqa3xih1(const PmRealVector *mc_82a3DKJG1OnqEvQnRrma62,const
PmSparsityPattern *mc_d9m7txhohSpkYAQKYp3sR1,const PmRealVector *
mc_frpbnk4Y0M4ZDQTQA_Say1,const PmSparsityPattern *mc__aqwF2UeMrHkDfRgGhMkr0,
const PmRealVector *mc_LvXhgCm6S5lTCS5qnZ0nL0,const PmSparsityPattern *
mc_VcKY7m0QAr85hALPtvLmC2,const PmRealVector *mc_8oHKE_vHwVdaX05lQda_c1);
PmSparsityPattern *mc_LFaZy0_889U2Wsk9bwBoz1(const PmSparsityPattern *
pm_9xuwQJgeHdekP5EKsGkzg0,const PmSparsityPattern *mc_8ErCt9pDoksttiAw9iBZp_,
PmAllocator *pm_an0wiQTjdlKE72zC6FJ0a2);typedef enum{mc_KhnGFEmutK29G1pFMV7eY2
= -1,mc_DKQ2NLbquneq0lUPeY6980,mc_pZ2gSv1PwNXkkpsIRojds1,
mc_s3f6TbPTFsg3OoFmSAmw9_,mc_UVVwEZg9VhYkMacmned87_,mc_We99sVwuHRSx58iJnCFWJ1,
mc_PlLsh29Os6JPlaG9RqaLj1}mc_v0sTqkEWafl9TPgVRJyQ40;typedef struct
mc_WhDlDj1zmiQx043biolb81 mc_GlmRlYa6s_WkfFpBYMHnW_;struct McRealFunctionTag{
mc_GlmRlYa6s_WkfFpBYMHnW_ *mc_2s9vB1TeGePozpYvhr_nm_;mc_v0sTqkEWafl9TPgVRJyQ40
(*mc_AkTbmaeNiVf6F7eo9cqvi0)(const void *mc_w2sbHOBWMTHvn1ViunNc91,const
PmRealVector *mc_ZFjwwXR9oOYOpGudG7a2f1,mc_GlmRlYa6s_WkfFpBYMHnW_ *
mc_6peHhhgu8wo0Kp3HDh_aI0);const void *(*mc_wlcTuDm2p66ascvFToGzq1)(const
McRealFunction *mc_Egr13MRE9IVP5BUwy4rIY1);void(*mc_YCFci8IAJkK9w_xpRtHta2)(
McRealFunction *mc_Egr13MRE9IVP5BUwy4rIY1);};typedef struct
mc_Owe6_gHWIwVgeopMGSBKl0 mc_aVw842GhQvd__vlWfLkt11;struct McIntFunctionTag{
mc_aVw842GhQvd__vlWfLkt11 *mc_2s9vB1TeGePozpYvhr_nm_;void(*
mc_AkTbmaeNiVf6F7eo9cqvi0)(const void *mc_w2sbHOBWMTHvn1ViunNc91,const
PmIntVector *mc_ZFjwwXR9oOYOpGudG7a2f1,mc_aVw842GhQvd__vlWfLkt11 *
mc_6peHhhgu8wo0Kp3HDh_aI0);const void *(*mc_wlcTuDm2p66ascvFToGzq1)(const
McIntFunction *mc_Egr13MRE9IVP5BUwy4rIY1);void(*mc_YCFci8IAJkK9w_xpRtHta2)(
McIntFunction *mc_Egr13MRE9IVP5BUwy4rIY1);};typedef struct
mc_yoIGOXVZU4sR6Ok75JMwh0 mc__mq5AHOLTsZs8aGf7Q6ee0;struct McMatrixFunctionTag
{mc__mq5AHOLTsZs8aGf7Q6ee0 *mc_2s9vB1TeGePozpYvhr_nm_;const PmSparsityPattern *
mc__iixD59voIPp_QZe1Ziof_;void(*mc_AkTbmaeNiVf6F7eo9cqvi0)(const void *
mc_w2sbHOBWMTHvn1ViunNc91,const PmRealVector *mc_ZFjwwXR9oOYOpGudG7a2f1,
mc__mq5AHOLTsZs8aGf7Q6ee0 *mc_6peHhhgu8wo0Kp3HDh_aI0);const void *(*
mc_wlcTuDm2p66ascvFToGzq1)(const McMatrixFunction *mc_Egr13MRE9IVP5BUwy4rIY1);
void(*mc_YCFci8IAJkK9w_xpRtHta2)(McMatrixFunction *mc_Egr13MRE9IVP5BUwy4rIY1);
};McMatrixFunction *mc_Gc2NB6_It3aMHmJd87WtV0(McMatrixFunction *
mc_DpmmNkDZIX2DRKnAC1cC21,size_t mc_N_EjeQp4WJPJRftR0Y3Cd1,size_t
mc_iFeOP4BSbdQmZZgCGP03i0,size_t mc_I98x_QlzPPBua1Isb8hyI0,size_t
mc_Q968L5leQKUG_5PDr9DIY2,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);typedef enum
{mc_Ujy2GzVXow1YEhzLJ7W8w0,mc_bInZ6XmbFSzmHBEOIg6_y_}mc_LmGErXKfbXqSyTLkEl3UX1
;McMatrixFunction *mc_DYHqOwnpTvvDXsUX3Ci520(McMatrixFunction *
mc_DpmmNkDZIX2DRKnAC1cC21,mc_LmGErXKfbXqSyTLkEl3UX1 type,size_t
mc_N_EjeQp4WJPJRftR0Y3Cd1,size_t mc_iFeOP4BSbdQmZZgCGP03i0,size_t
mc_I98x_QlzPPBua1Isb8hyI0,size_t mc_Q968L5leQKUG_5PDr9DIY2,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);McMatrixFunction *mc_Gc2NB6_It3aMHmJd87WtV0(
McMatrixFunction *mc_nR_rjMeLaWSWsbSb51dZx1,size_t mc_N_EjeQp4WJPJRftR0Y3Cd1,
size_t mc_iFeOP4BSbdQmZZgCGP03i0,size_t mc_I98x_QlzPPBua1Isb8hyI0,size_t
mc_Q968L5leQKUG_5PDr9DIY2,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2){return
mc_DYHqOwnpTvvDXsUX3Ci520(mc_nR_rjMeLaWSWsbSb51dZx1,mc_Ujy2GzVXow1YEhzLJ7W8w0,
mc_N_EjeQp4WJPJRftR0Y3Cd1,mc_iFeOP4BSbdQmZZgCGP03i0,mc_I98x_QlzPPBua1Isb8hyI0,
mc_Q968L5leQKUG_5PDr9DIY2,pm_WFHqm0fOpgfhKZFbY5NWh2);}
