#include "pm_std.h"
#include "pm_std.h"
#include "mc_std.h"
#include "ne_std.h"
#include "mc_std.h"
typedef struct ssc_core_apWKlSiqYlOEuzjHKc5GX2 ssc_core_7Gx_dh5Tki38AkADLkE2H1
;typedef struct ssc_core_UobhgC__LOfn05I_A6cSj2 ssc_core__OM7G9uJF4tZY9vaH_Qv_1
;struct ssc_core_UobhgC__LOfn05I_A6cSj2{boolean_T(*
ssc_core_r3XTQSiIyT97jRZuxAZzV_)(const ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *
ssc_core_aTYoAWr1REqCeqF3MxzWA1,const NeSystemInput *mc_w2sbHOBWMTHvn1ViunNc91
);void(*mc_YCFci8IAJkK9w_xpRtHta2)(ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *
ssc_core_aTYoAWr1REqCeqF3MxzWA1);ssc_core_7Gx_dh5Tki38AkADLkE2H1 *
mc_0TyJOxmrCFOwXODumYaSw2;};ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *
ssc_core_dhrA8zmAPxlQneG4eVGDJ2(NeSystemInputSizes ne_18op92eXGiCTt3cPVSrLy_,
PmAllocator *pm_an0wiQTjdlKE72zC6FJ0a2);void pm_rv_equals_rv(const PmRealVector
*pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector *pm__UmJPtGaW9C9junx1RpnH_);void
pm_U1h5Sl4yTxoF_YCvN9hBa1(const PmIntVector *pm_JMQ_js3toioP0_0hj_fm5_,const
PmIntVector *pm__UmJPtGaW9C9junx1RpnH_);void pm_TnPSeUZeYw5Wc8bvD8sl80(const
PmBoolVector *pm_JMQ_js3toioP0_0hj_fm5_,const PmBoolVector *
pm__UmJPtGaW9C9junx1RpnH_);void pm_fKS8kuV7G_WhlO7CcdVnc1(const PmCharVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmCharVector *pm__UmJPtGaW9C9junx1RpnH_);
boolean_T pm___43lXp90F4bzSkAXqYfT1(const PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector *pm__UmJPtGaW9C9junx1RpnH_);
boolean_T pm_XDtBnYqrul1zO7ccbIlmV2(const PmIntVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector *pm__UmJPtGaW9C9junx1RpnH_);
boolean_T pm_9IegWBFmNW3wA_0fRmj9m2(const PmBoolVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmBoolVector *pm__UmJPtGaW9C9junx1RpnH_);int_T
pm_create_real_vector_fields(PmRealVector *pm_VmBquL1cTEkIgP0cS5pM82,size_t
size,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);PmRealVector *
pm_create_real_vector(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);PmRealVector *pm_ZdJ6KB36NX_7JjULh6fi72(const
PmRealVector *pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2
);void pm_MgDXCYHfYCiNYyF5Ik7dF2(PmRealVector *pm_VmBquL1cTEkIgP0cS5pM82,
PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_destroy_real_vector(
PmRealVector *pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2
);int_T pm_create_int_vector_fields(PmIntVector *pm_VmBquL1cTEkIgP0cS5pM82,
size_t size,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);PmIntVector *
pm_create_int_vector(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);PmIntVector *pm_pLia5sG_NxTeQbxzYtpXx_(const
PmIntVector *pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2)
;void pm_Rdk2CZ3CCj5T0d2uDHUZ20(PmIntVector *pm_VmBquL1cTEkIgP0cS5pM82,
PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_destroy_int_vector(PmIntVector
*pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);int_T
pm_create_bool_vector_fields(PmBoolVector *pm_VmBquL1cTEkIgP0cS5pM82,size_t
size,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);PmBoolVector *
pm_YZQHxvtiv5rBT_iBt45HQ_(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_SK8Vck8jU45BIyJDK11DV_(PmBoolVector *
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_qv4zOCjtiVRVC86eoqx06_(PmBoolVector *pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);PmBoolVector *pm_Or6MViYTj4_1rM_3pn1UZ0(const
PmBoolVector *pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2
);int_T pm_create_char_vector_fields(PmCharVector *pm_VmBquL1cTEkIgP0cS5pM82,
size_t size,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);PmCharVector *
pm_VJ_YkZBOp_Ry9yis8LShD1(size_t pm_Z_HH1rAAmOFPWVcI_yamd_,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);void pm_cn_kUNHZ0hjihWokUKapj_(PmCharVector *
pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *pm_WFHqm0fOpgfhKZFbY5NWh2);void
pm_ea51z6lAUjevRfjOCHL37_(PmCharVector *pm_VmBquL1cTEkIgP0cS5pM82,PmAllocator *
pm_WFHqm0fOpgfhKZFbY5NWh2);size_t mc_KpKqaZjZ2rh3lSToFa7Oa2(const PmBoolVector
*mc_ljExW6hRw43Vg4SLQUAvT1);void mc_KLKWK_FbEAF724qPNbehq1(const PmIntVector *
mc_ykDPEcD4BuT8SJa7vuxej1,const PmRealVector *x,real_T
mc_s3INuDyUdU1QdPspAeWD81);void mc_uJ_iGAyluQ5NndhonaPXl1(const PmIntVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector *pm__UmJPtGaW9C9junx1RpnH_,const
PmIntVector *mc_kmcnrlTt6IvFH5HSoyHe21);void mc_oT_HwSgZBfR7LPqZomt0Y0(const
PmIntVector *pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector *
pm__UmJPtGaW9C9junx1RpnH_,const PmIntVector *mc_kmcnrlTt6IvFH5HSoyHe21);void
mc_mMmDjYPdSIEEQHj__7cd71(const PmIntVector *pm_JMQ_js3toioP0_0hj_fm5_);void
mc_zYvj4jole4TnufsPoZWW_2(const PmIntVector *pm_JMQ_js3toioP0_0hj_fm5_,const
PmIntVector *pm__UmJPtGaW9C9junx1RpnH_,const PmBoolVector *
mc_i34rFP0sHa_dTbFseidcw0);void mc_TJe2EtJyyhfHpuJYOjxfC0(const PmIntVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector *pm__UmJPtGaW9C9junx1RpnH_,
boolean_T mc_7lBL31aWjgSfMHGQtksob2);void mc_JM1DLKwRGzo9Uyq32V72E_(const
PmIntVector *pm_JMQ_js3toioP0_0hj_fm5_,const PmIntVector *
mc_MmlNWCb0Iec292kl7KbkQ1);void mc_si_irLJWyQLY_l4tqebAe_(const PmIntVector *
mc_rxT7_6KqJcx5sNYEWRALX2,int32_T mc_RGllRMvIRPGkpbvuetJlO2);void
mc_pJmDkwzzX3Iu6_VR_MyvL_(const PmBoolVector *mc_Hf_a_gs1wyoHoosYiGonU0,const
PmBoolVector *mc_AV_LMGONnBUCahwCg3D4y_,const PmIntVector *
mc_YwEOIpm092vI_BA0rQzvJ2);void mc_SKE1EUStKD_KtRTTXrxqv2(const PmBoolVector *
mc_9_yWAFd98YjxIPCHmG5rr0,size_t mc__VPpmCt_TuqLdOtTsmwgk2,const PmBoolVector *
mc_Ds0gTsuf_v_EnBO9LqpvK_,size_t mc_947YwtWZMq1Crv_q1N3191,size_t
pm_QHNSjd8JBrVVYZAcs7Zm32);void mc_OT_v_IC_x9R85Z4eHn1jA0(const PmRealVector *
mc_9_yWAFd98YjxIPCHmG5rr0,size_t mc__VPpmCt_TuqLdOtTsmwgk2,const PmRealVector *
mc_Ds0gTsuf_v_EnBO9LqpvK_,size_t mc_947YwtWZMq1Crv_q1N3191,size_t
pm_QHNSjd8JBrVVYZAcs7Zm32);void mc_J9HotRGeuZtxiip_GSZPb0(PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector *pm__UmJPtGaW9C9junx1RpnH_);
size_t mc_lp5J2bZ8EcxnhyI1PKPZd2(const PmBoolVector *mc_G15g52JPQFeDaEm_uJadW_
);void mc__xr97Mh4VU4bdE2CcyEVf_(const PmIntVector *mc_YwEOIpm092vI_BA0rQzvJ2,
const PmBoolVector *mc_AV_LMGONnBUCahwCg3D4y_);size_t mc_pdD80p5I4a4oDKki08oZ50
(const PmIntVector *mc_kI6kqxnpJaUqvLfVbMkdr0);size_t mc_a_dd0x8Rstf0HD74BJt9A2
(const PmRealVector *mc_ZxltZcnt1eSoyJTnrOm7z2);size_t
mc_8u8_LRBN9SbcEOkeum7ag0(const PmBoolVector *mc_ZxltZcnt1eSoyJTnrOm7z2);
boolean_T mc_Ukc2BYyTIIZDpb_lFOWTt0(const PmIntVector *
mc_kI6kqxnpJaUqvLfVbMkdr0);boolean_T mc_l26oJh0UM_xwSgKIeOC5J0(const
PmIntVector *pm_JMQ_js3toioP0_0hj_fm5_,int32_T mc_RGllRMvIRPGkpbvuetJlO2);
boolean_T mc_ocDPr6f6C4_v9b5NDj8JH_(const PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_,real_T mc_RGllRMvIRPGkpbvuetJlO2);void
mc_fuQc8C9CyCuf_KkBLV8eb0(const PmRealVector *pm_JMQ_js3toioP0_0hj_fm5_,const
PmRealVector *pm__UmJPtGaW9C9junx1RpnH_);void mc_8BTcsQ6C8h5zrW1ZQRhKf1(const
PmRealVector *x,real_T mc_ljExW6hRw43Vg4SLQUAvT1);void
mc_W0fX8K54ez0qAgM9tXjsi_(const PmRealVector *x,const PmRealVector *
mc_ET9_5EAP116KvP5KVqsrD2);void mc_fjtK_RGCYgp34_TjPN6zv1(const PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector *pm__UmJPtGaW9C9junx1RpnH_);void
mc_LlLyVwCApgTvSBfIvzOuk0(const PmRealVector *pm_JMQ_js3toioP0_0hj_fm5_,real_T
pm_9xuwQJgeHdekP5EKsGkzg0,const PmRealVector *pm__UmJPtGaW9C9junx1RpnH_);void
mc_fIL9UyKjuKeUlnGmcXq5r2(const PmRealVector *x,const PmRealVector *
mc_ET9_5EAP116KvP5KVqsrD2,const PmRealVector *mc_SheEjf_3lOXDmgzkmhMGG2);void
mc_v7V5uZPqLRlsEpMCWsoMJ0(const PmRealVector *x,const real_T
pm_9xuwQJgeHdekP5EKsGkzg0,const PmRealVector *mc_ET9_5EAP116KvP5KVqsrD2);void
mc_DnL_y_DaeSoRsDtnK0hpB1(const PmRealVector *pm_JMQ_js3toioP0_0hj_fm5_,const
real_T mc_8IKoYx3qsjeiwHerWlCOS1);void mc_I_W_409sg28ysFYlBfPcr_(const
PmRealVector *pm_JMQ_js3toioP0_0hj_fm5_,const real_T mc_8IKoYx3qsjeiwHerWlCOS1
);void mc_MI5F4RaYNQR7pPk1GRkvn_(const PmIntVector *pm_JMQ_js3toioP0_0hj_fm5_,
const PmIntVector *pm__UmJPtGaW9C9junx1RpnH_);void mc_lkC6x3YtrvW6L16S6aM60_(
const PmRealVector *pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector *
pm__UmJPtGaW9C9junx1RpnH_);void mc_vfuXLuRk3KtAfbvK_cTrv2(const PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector *pm__UmJPtGaW9C9junx1RpnH_);void
mc_tOKZMGNlSqK650YhjgeKv0(const PmRealVector *mc_9JsNfMLIQx0SlNuEaL4I2_,real_T
mc_8IKoYx3qsjeiwHerWlCOS1);void mc_Uy10YSjkY75ViJd9dTdYI1(const PmBoolVector *
mc_9JsNfMLIQx0SlNuEaL4I2_);void mc_Rhhlgu4QH_WTKd_5kpe4I2(const PmRealVector *
mc_9JsNfMLIQx0SlNuEaL4I2_);void mc_WmHTznO_Ih_dJw_MhKtIQ1(const PmIntVector *
mc_9JsNfMLIQx0SlNuEaL4I2_,int32_T mc_RGllRMvIRPGkpbvuetJlO2);void
mc_nLc17gFNFcvBlJrwxJV4w_(const PmIntVector *mc_9JsNfMLIQx0SlNuEaL4I2_);void
mc_W7kR8viSTKC_By0UjXE_A1(const PmIntVector *mc_9JsNfMLIQx0SlNuEaL4I2_);void
mc_AQtCbBjZ792h1_Xaj_dR92(const PmBoolVector *mc_i34rFP0sHa_dTbFseidcw0,const
PmIntVector *mc_YwEOIpm092vI_BA0rQzvJ2,boolean_T mc_8IKoYx3qsjeiwHerWlCOS1);
void mc_tLxHiRii5tbHWjrunaI2i1(const PmBoolVector *mc_9JsNfMLIQx0SlNuEaL4I2_,
boolean_T mc_8IKoYx3qsjeiwHerWlCOS1);void mc_AZRifAjle326aZku91XJU2(const
PmBoolVector *mc_9JsNfMLIQx0SlNuEaL4I2_);void mc_mGD4FL6_MDLg2bdqzdpfx_(const
PmBoolVector *x,size_t pm_SmSSPSQfR1qEYWsVj5ELF0,size_t
pm_QHNSjd8JBrVVYZAcs7Zm32);void mc_x2bRmxKlHWAMEwOZuiA_62(const PmBoolVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmBoolVector *pm__UmJPtGaW9C9junx1RpnH_);void
mc_eJ9VFRIFMWxO52_BT7X_C_(const PmBoolVector *pm_JMQ_js3toioP0_0hj_fm5_,const
PmBoolVector *pm__UmJPtGaW9C9junx1RpnH_);real_T mc_WJAbbKueqClxuItYQx7b61(
const PmRealVector *pm_JMQ_js3toioP0_0hj_fm5_);real_T mc_TuU8NakpY91qxLM4is2wV2
(const PmRealVector *pm_VmBquL1cTEkIgP0cS5pM82);int32_T
mc_dLmR9a64iWQBHX4QM5zCr2(const PmIntVector *pm_VmBquL1cTEkIgP0cS5pM82);
int32_T mc_eIjmwucqCUJT1PyCl_z5b_(const PmIntVector *pm_VmBquL1cTEkIgP0cS5pM82
);void mc_loSQGFba0sjWysbLdmqzS1(PmIntVector *pm_QyVbO3pTvGiccU8Tn2eK2_,const
PmIntVector *mc_kI6kqxnpJaUqvLfVbMkdr0);void mc_O_flPmjeFB4ZmON9Xp2iV_(
PmRealVector *mc_EBUUePJ08d2hXtTa8LU0J_,const PmRealVector *
mc_23nxQONnTNHWizowC7lIt0,const PmSparsityPattern *mc_UYX2aVqEUCl0fW5_qT4Lo1);
void mc_K1ezq3TzhoNUE_SEp0Dr12(const PmRealVector *mc_kvOR3Cr3RdA0t5JHDRjvp1,
const PmSparsityPattern *mc_73ubi6fCtM2UVxkG602gl0,const PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_);void mc_WuGlfcFda9zO01qKeAxMn_(const PmRealVector *
pm__UmJPtGaW9C9junx1RpnH_,const PmRealVector *mc_kvOR3Cr3RdA0t5JHDRjvp1,const
PmSparsityPattern *mc_73ubi6fCtM2UVxkG602gl0,const PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_);void mc_qEYnRq0Ff87lxOQck1Gqi_(const PmRealVector *
pm__UmJPtGaW9C9junx1RpnH_,const PmRealVector *mc_kvOR3Cr3RdA0t5JHDRjvp1,const
PmSparsityPattern *mc_73ubi6fCtM2UVxkG602gl0,const real_T *x);void
mc_SZGAWN4U4XTzc5RKGKSk5_(const PmRealVector *pm__UmJPtGaW9C9junx1RpnH_,const
PmRealVector *mc_kvOR3Cr3RdA0t5JHDRjvp1,const PmSparsityPattern *
mc_73ubi6fCtM2UVxkG602gl0,const PmRealVector *mc_2cVF0Ggof80TSRmRbhE8l1,size_t
mc_LMkPrnaKcsYHEp0eExPFH1);void mc_FoRQvfcV_dWdjx5L1lyM_0(const PmRealVector *
pm__UmJPtGaW9C9junx1RpnH_,const PmRealVector *mc_kvOR3Cr3RdA0t5JHDRjvp1,const
PmSparsityPattern *mc_73ubi6fCtM2UVxkG602gl0,const PmRealVector *
pm_JMQ_js3toioP0_0hj_fm5_,const PmRealVector *mc_5LkYradW8mKeL3fLSt9By1);void
mc_z041e_QXd3uR2ef2CH37s1(const PmRealVector *mc_ET9_5EAP116KvP5KVqsrD2,const
PmRealVector *mc_0R8y9UtrLk3busEbM65xW_,const PmSparsityPattern *
mc__aqwF2UeMrHkDfRgGhMkr0,size_t pm_OUB2pptsvtdGL_LyqpgOa0,real_T
mc_8IKoYx3qsjeiwHerWlCOS1);void mc_6IsBGrycIJELSxeQVWGP02(const PmRealVector *
mc_SheEjf_3lOXDmgzkmhMGG2,const PmRealVector *x,const PmRealVector *
mc_ET9_5EAP116KvP5KVqsrD2);void mc_fDK_uVHGu_qFAztUmYrXG0(const PmRealVector *
mc_Hf_a_gs1wyoHoosYiGonU0,const PmRealVector *mc_AV_LMGONnBUCahwCg3D4y_,const
PmIntVector *mc_Ma839gzucrzsXwGyDhMa82);void mc_Pv5PxBp1nNTpA2nv2TKO50(const
PmRealVector *mc_Hf_a_gs1wyoHoosYiGonU0,const PmIntVector *
mc_Ma839gzucrzsXwGyDhMa82,const PmRealVector *mc_AV_LMGONnBUCahwCg3D4y_);void
mc_57l_YQYSoo0Ro6WNuRptH_(const PmRealVector *pm_9xuwQJgeHdekP5EKsGkzg0,const
PmIntVector *pm_SmSSPSQfR1qEYWsVj5ELF0,const PmRealVector *
mc_8ErCt9pDoksttiAw9iBZp_);void mc_rQYUV3yV8oYU8KnRKkDRk1(const PmRealVector *
pm_9xuwQJgeHdekP5EKsGkzg0,const PmRealVector *mc_8ErCt9pDoksttiAw9iBZp_,const
PmBoolVector *pm_SmSSPSQfR1qEYWsVj5ELF0);void mc_Xx__kIPwzSZkrHpStVmJF_(const
PmRealVector *pm_9xuwQJgeHdekP5EKsGkzg0,const PmBoolVector *
pm_SmSSPSQfR1qEYWsVj5ELF0,const PmRealVector *mc_8ErCt9pDoksttiAw9iBZp_);void
mc__oSPLVBiXeFzzJsThp3Cn_(const PmRealVector *pm_9xuwQJgeHdekP5EKsGkzg0,const
PmBoolVector *pm_SmSSPSQfR1qEYWsVj5ELF0,real_T x);void
mc_BtNbeiWJf_2ScS2FihDGI0(const PmIntVector *mc_Fgipzm4dZtWjNvleXva_V1,const
PmSparsityPattern *mc_wgw5_klFOULlYUS4qsiDG1);void mc_rxnwynr09yoIhr_7WJOnw2(
const PmBoolVector *mc_Fgipzm4dZtWjNvleXva_V1,const PmSparsityPattern *
mc_wgw5_klFOULlYUS4qsiDG1);void mc_GXd0l4NyYg6UNbaEbfuyY1(const PmBoolVector *
mc_Fgipzm4dZtWjNvleXva_V1,const PmSparsityPattern *mc_wgw5_klFOULlYUS4qsiDG1);
void mc_0IN6lZI7UaPeQvvz13t6Z_(const PmBoolVector *mc_Fgipzm4dZtWjNvleXva_V1,
const PmSparsityPattern *mc_wgw5_klFOULlYUS4qsiDG1);void
mc_jk3AE9w8Z153JpwqOK4cP_(const PmBoolVector *pm_v4k0LG4l9Qk9hEXlOIKML_,const
PmSparsityPattern *pm_3fmwBoA2gfKGlaDfp8GCd1,const PmRealVector *
mc_A1lUr3Ax9HoRb_bkcLe_A1);void mc_PUtu_CUnyMAexj3n9ThPz1(const PmBoolVector *
pm__UmJPtGaW9C9junx1RpnH_,const PmSparsityPattern *mc_73ubi6fCtM2UVxkG602gl0,
const PmBoolVector *pm_JMQ_js3toioP0_0hj_fm5_);void mc_wMbxp0k7MHKEjpdy17fjt_(
const PmRealVector *mc_jJ78FsEfvlTthTdupUhHD2,const PmSparsityPattern *
pm_3fmwBoA2gfKGlaDfp8GCd1,const PmBoolVector *mc_ID3sxM8zmIB_ZiazgNvWq2);void
mc_5PAUXWifOqPPHW3wOzFa92(const PmRealVector *mc_jJ78FsEfvlTthTdupUhHD2,const
PmSparsityPattern *pm_3fmwBoA2gfKGlaDfp8GCd1,const PmBoolVector *
pm_gq3kPpO4Hdv_0UBmX5sfB1);PmRealVector mc_mnPo3YlQdExsVqjHael_W2(const
PmRealVector *mc_ljExW6hRw43Vg4SLQUAvT1,size_t mc_XteRrKcywHWBP4sFymZ6y0,
size_t mc_jcOSsrULtHDGKqSRz3gAT0);struct ssc_core_apWKlSiqYlOEuzjHKc5GX2{
PmIntVector *ssc_core_vUn_KOYFa7SUrBuJzK_F61;PmRealVector *
ssc_core_w6uXhgAoPsTIJVrqeDQk__;boolean_T ssc_core_Q_Q89nCaKVGjQse6RFYIu1;
PmAllocator *mc_EJyLFJLNS54LEp1_ia1250;};static boolean_T
ssc_core_kDJGKeSTzftk4Fx2VZp2V_(const ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *
ssc_core_aTYoAWr1REqCeqF3MxzWA1,const NeSystemInput *mc_w2sbHOBWMTHvn1ViunNc91
){boolean_T ssc_core_Zi_guOuqiDZ2lysAfLyEq2=(0);
ssc_core_7Gx_dh5Tki38AkADLkE2H1 *mc_6peHhhgu8wo0Kp3HDh_aI0=
ssc_core_aTYoAWr1REqCeqF3MxzWA1->mc_0TyJOxmrCFOwXODumYaSw2;if(
mc_6peHhhgu8wo0Kp3HDh_aI0->ssc_core_Q_Q89nCaKVGjQse6RFYIu1){
ssc_core_Zi_guOuqiDZ2lysAfLyEq2=(1);mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_Q_Q89nCaKVGjQse6RFYIu1=(0);pm_U1h5Sl4yTxoF_YCvN9hBa1(
mc_6peHhhgu8wo0Kp3HDh_aI0->ssc_core_vUn_KOYFa7SUrBuJzK_F61,&
mc_w2sbHOBWMTHvn1ViunNc91->mQ);pm_rv_equals_rv(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_w6uXhgAoPsTIJVrqeDQk__,&mc_w2sbHOBWMTHvn1ViunNc91->mD);}else if(!
pm_XDtBnYqrul1zO7ccbIlmV2(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_vUn_KOYFa7SUrBuJzK_F61,&mc_w2sbHOBWMTHvn1ViunNc91->mQ)||!
pm___43lXp90F4bzSkAXqYfT1(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_w6uXhgAoPsTIJVrqeDQk__,&mc_w2sbHOBWMTHvn1ViunNc91->mD)){
ssc_core_Zi_guOuqiDZ2lysAfLyEq2=(1);pm_U1h5Sl4yTxoF_YCvN9hBa1(
mc_6peHhhgu8wo0Kp3HDh_aI0->ssc_core_vUn_KOYFa7SUrBuJzK_F61,&
mc_w2sbHOBWMTHvn1ViunNc91->mQ);pm_rv_equals_rv(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_w6uXhgAoPsTIJVrqeDQk__,&mc_w2sbHOBWMTHvn1ViunNc91->mD);}return
ssc_core_Zi_guOuqiDZ2lysAfLyEq2;}static void ssc_core_Clylum_FvI3A4t2pE2Yoy1(
ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *ssc_core_aTYoAWr1REqCeqF3MxzWA1){
ssc_core_7Gx_dh5Tki38AkADLkE2H1 *mc_6peHhhgu8wo0Kp3HDh_aI0=
ssc_core_aTYoAWr1REqCeqF3MxzWA1->mc_0TyJOxmrCFOwXODumYaSw2;PmAllocator *
pm_an0wiQTjdlKE72zC6FJ0a2= mc_6peHhhgu8wo0Kp3HDh_aI0->
mc_EJyLFJLNS54LEp1_ia1250;pm_destroy_int_vector(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_vUn_KOYFa7SUrBuJzK_F61,pm_an0wiQTjdlKE72zC6FJ0a2);
pm_destroy_real_vector(mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_w6uXhgAoPsTIJVrqeDQk__,pm_an0wiQTjdlKE72zC6FJ0a2);{void *
pm_GAbHnJspJ6sMhe_Yzxehb_=(mc_6peHhhgu8wo0Kp3HDh_aI0);if(
pm_GAbHnJspJ6sMhe_Yzxehb_!=0){(pm_an0wiQTjdlKE72zC6FJ0a2)->mFreeFcn(
pm_an0wiQTjdlKE72zC6FJ0a2,pm_GAbHnJspJ6sMhe_Yzxehb_);}};{void *
pm_GAbHnJspJ6sMhe_Yzxehb_=(ssc_core_aTYoAWr1REqCeqF3MxzWA1);if(
pm_GAbHnJspJ6sMhe_Yzxehb_!=0){(pm_an0wiQTjdlKE72zC6FJ0a2)->mFreeFcn(
pm_an0wiQTjdlKE72zC6FJ0a2,pm_GAbHnJspJ6sMhe_Yzxehb_);}};}
ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *ssc_core_dhrA8zmAPxlQneG4eVGDJ2(
NeSystemInputSizes ne_18op92eXGiCTt3cPVSrLy_,PmAllocator *
pm_an0wiQTjdlKE72zC6FJ0a2){ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *
ssc_core_aTYoAWr1REqCeqF3MxzWA1=(ssc_core__OM7G9uJF4tZY9vaH_Qv_1 *)((
pm_an0wiQTjdlKE72zC6FJ0a2)->mCallocFcn((pm_an0wiQTjdlKE72zC6FJ0a2),(sizeof(
ssc_core__OM7G9uJF4tZY9vaH_Qv_1)),(1)));ssc_core_7Gx_dh5Tki38AkADLkE2H1 *
mc_6peHhhgu8wo0Kp3HDh_aI0=(ssc_core_7Gx_dh5Tki38AkADLkE2H1 *)((
pm_an0wiQTjdlKE72zC6FJ0a2)->mCallocFcn((pm_an0wiQTjdlKE72zC6FJ0a2),(sizeof(
ssc_core_7Gx_dh5Tki38AkADLkE2H1)),(1)));mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_vUn_KOYFa7SUrBuJzK_F61= pm_create_int_vector(
ne_18op92eXGiCTt3cPVSrLy_.mSizes[NE_SYSTEM_INPUT_ID_Q],
pm_an0wiQTjdlKE72zC6FJ0a2);mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_w6uXhgAoPsTIJVrqeDQk__= pm_create_real_vector(
ne_18op92eXGiCTt3cPVSrLy_.mSizes[NE_SYSTEM_INPUT_ID_D],
pm_an0wiQTjdlKE72zC6FJ0a2);mc_6peHhhgu8wo0Kp3HDh_aI0->
ssc_core_Q_Q89nCaKVGjQse6RFYIu1=(1);mc_6peHhhgu8wo0Kp3HDh_aI0->
mc_EJyLFJLNS54LEp1_ia1250= pm_an0wiQTjdlKE72zC6FJ0a2;
ssc_core_aTYoAWr1REqCeqF3MxzWA1->ssc_core_r3XTQSiIyT97jRZuxAZzV_=
ssc_core_kDJGKeSTzftk4Fx2VZp2V_;ssc_core_aTYoAWr1REqCeqF3MxzWA1->
mc_YCFci8IAJkK9w_xpRtHta2= ssc_core_Clylum_FvI3A4t2pE2Yoy1;
ssc_core_aTYoAWr1REqCeqF3MxzWA1->mc_0TyJOxmrCFOwXODumYaSw2=
mc_6peHhhgu8wo0Kp3HDh_aI0;return ssc_core_aTYoAWr1REqCeqF3MxzWA1;}
